version: '3.8'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    environment:
      MYSQL_DATABASE: youcourse
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - c:\youcourse\db:/var/lib/mysql
    ports:
      - "33061:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - youcourse_esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  youcourse_esdata: